### ISSUE TITLE
Необоснованная цензура специально для ру-сегмента

### ISSUE THREAD

**Issue by hugmouse** [natribu/natribu.org#13]
Данные изменения сильно задевают стилистику сайта, суть его существования и этику.

Следующие коммиты: 98807e88bf69c36802fb14990e4d1e5aedf80b6a, 936792515ccea9abdcd6d94bd05a97d5b1c22938, 7e5732609ab056b9f305649538c59831bc0b1a27, 0100aec561f93d62cdfc28471df693c97be8397c являются необоснованной цензурой.

Сайт так же не является СМИ, [чтобы цензурить мат](https://base.garant.ru/70353432/1cafb24d049dcd1e7707a22d98e9858f/#block_1).

В следствии чего я хочу, чтобы вы объяснили с чем связана данная цензура специально для ру-сегмента интернета. А лучше - вообще убрать ее.

**Comment by sozidatel** [comment]
Ох, как вы правы.
Но у меня нет никаких ресурсов бодаться в росцензурой и не хочется закрывать сайт от российских пользователей.
Подробности тут: https://m.facebook.com/story.php?story_fbid=10219868990252346&id=1148451041

**Comment by sozidatel** [comment]
https://natribu.org/?fuck_rkn, и другие варианты, как вы могли заметить в коммитах.

**Comment by hugmouse** [comment]
Это очень грустно :(
> Ох, как вы правы.
> Но у меня нет никаких ресурсов бодаться в росцензурой и не хочется закрывать сайт от российских пользователей.
> Подробности тут: https://m.facebook.com/story.php?story_fbid=10219868990252346&id=1148451041

**Comment by sozidatel** [comment]
В то время, когда в России обычным людям дают реальные сроки за вообще ничего, как-то не к месту поднимать бучу из-за скромного официального сайта символического направления.

Но если вдруг Агора, или просто высоко-активный гражданин решит защитить право россиян на НАХУЙ, то это было бы чудесно.

Сейчас же есть РКН, и есть решение тамбовского суда. Сайт уже в списках, но доступ к нему пока не блокируется. В теории, ятак понял, в РКН должны перпроверить содержание, увидеть звёздочки и вроде как удалят из списков. Или так и будут ходить НАХУЙ каждый божий день и проверять его скромность…
