### ISSUE TITLE
Сайт заблокирован

### ISSUE THREAD

**Issue by Saiv46** [natribu/natribu.org#15]
Сайт уже блокируется провайдерами, несмотря на #13
Но как не странно - HTTPS-версия работает, но звёздочки глаза мозолят

**Comment by sozidatel** [comment]
Прямо контрастный душ из новостей.

Звёздочки убираются легко: https://natribu.org/?fuck_rkn
Ну или https://natribu.org/?420, например.

**Comment by sozidatel** [comment]
Добавил HTTP Strict Transport Security, теперь достаточно хоть раз зайти на сайт.
Сделал чтобы цензура отключалась при любом содержимом в части Query String.

**Comment by Linda-chan** [comment]
Про вас пишут.

http://www.duralex.org/2019/10/10/na-temu-necenzurnoj-brani-i-ee-roli-v-narabotke-prokurorskix-pokazatelej/

Я же никаких звёздочек не наблюдаю.

**Comment by Saiv46** [comment]
Оказывается, РКН может дать бан даже при цензуре со звёздочками: https://t.co/WgbRNJWJES

**Comment by iulh** [comment]
я так понимаю что теперь кроме как VPNом больше дельных способов нет, да?

**Comment by Saiv46** [comment]
@sozidatel Блокировки на поддомены распространяются? Надо проверить на домене типа `idi.natribu.org`
