### ISSUE TITLE
Редактор

### ISSUE THREAD

**Issue by gtimoshaz** [natribu/natribu.org#3]
Когда я хочу послать друга, мне предлагается скачать editor, вместо того чтобы открыть страницу с ним
страница http://natribu.org/editor

**Comment by sozidatel** [comment]
Похоже nginx хулиганит. 
С первого взгляда не понял, попробую разобраться.

**Comment by sozidatel** [comment]
Не, nginx не был виноват. Там на самом деле тупо лежал файл editor со словом editor внутри.
А потом и в самом редакторе ошибки.
