### ISSUE TITLE
Избавиться от флеша

### ISSUE THREAD

**Issue by micronull** [natribu/natribu.org#5]
2016й все таки.

**Comment by sozidatel** [comment]
А что, там требование флеша?
Безобразие..

**Comment by ghost** [comment]
фууу флеш...

**Comment by ghost** [comment]
Флеш можно заменить html-кодом:
```
<audio autoplay="" src="http://natribu.org/media/na.mp3"></audio>
<img src="http://beliy.ru/private/master_comment/na.gif" width=20 height=27 border=0>
```

**Comment by ghost** [comment]
фу хуйня

**Comment by sozidatel** [comment]
@45Green, хочется ещё сохранить анимацию. Только начал переводить в анимированный SVG, как он deprecated :-(

**Comment by ghost** [comment]
@sozidatel, алло!
GIF в img всё равно будет анимированным.

**Comment by good-old-times** [comment]
Я могу все переписать

**Comment by sozidatel** [comment]
@misha-marinenko-official, всё-не-всё, а звуко-анимационную часть было бы круто.
Давай!

**Comment by KOLANICH** [comment]
damn, it's 2019 and this is still not finished

**Comment by sozidatel** [comment]
Избавились, раз уж такое дело.
Не уверен, что MP3 выдернул лучшим образом из SWF (тут благодарность VLC плееру), может можно и покачественнее было сделать.
